// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeuZQhZsQNqH9A7HlfgNAF3C3sDtsfR0',
    appId: '1:978563030549:web:bf8c9af91a526b2ee8781c',
    messagingSenderId: '978563030549',
    projectId: 'ecommerce-bcade',
    authDomain: 'ecommerce-bcade.firebaseapp.com',
    storageBucket: 'ecommerce-bcade.firebasestorage.app',
    measurementId: 'G-04E4QLCEWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqICOpnEDpmDmNA5JfjV8U-DCov8Cvn1E',
    appId: '1:978563030549:android:e4238192171e0f4fe8781c',
    messagingSenderId: '978563030549',
    projectId: 'ecommerce-bcade',
    storageBucket: 'ecommerce-bcade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGuPNZK7mRobDLKxSP90AC1B_vvA4sp8',
    appId: '1:978563030549:ios:84452cc1905bd491e8781c',
    messagingSenderId: '978563030549',
    projectId: 'ecommerce-bcade',
    storageBucket: 'ecommerce-bcade.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdmin',
  );
}
